facilityList = [
  '{"facility":"ALL","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ALL+Canada","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"Manual","tier":"Manual","depFacilities":""}',
  '{"facility":"ZAB","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZAB","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZAB","tier":"1stTier","depFacilities":"ZAB ZLA ZDV ZKC ZFW ZHU"}',
  '{"facility":"ZAB","tier":"1stTier+Canada","depFacilities":"ZAB ZLA ZDV ZKC ZFW ZHU"}',
  '{"facility":"ZAB","tier":"2ndTier","depFacilities":"ZAB ZLA ZDV ZKC ZFW ZHU ZOA ZLC ZMP ZAU ZID ZME ZTL ZJX"}',
  '{"facility":"ZAB","tier":"2ndTier+Canada","depFacilities":"ZAB ZLA ZDV ZKC ZFW ZHU ZOA ZLC ZMP ZAU ZID ZME ZTL ZJX"}',
  '{"facility":"ZAB","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZAB","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZAB","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZAB","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZAB","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZAB","tier":"Internal","depFacilities":"ZAB"}',
  '{"facility":"ZAB","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZAU","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZAU","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZAU","tier":"1stTier","depFacilities":"ZAU ZMP ZKC ZID ZOB"}',
  '{"facility":"ZAU","tier":"1stTier+Canada","depFacilities":"ZAU ZMP ZKC ZID ZOB"}',
  '{"facility":"ZAU","tier":"2ndTier","depFacilities":"ZAU ZMP ZKC ZID ZOB ZLC ZDV ZAB ZFW ZME ZTL ZDC ZNY ZBW"}',
  '{"facility":"ZAU","tier":"2ndTier+Canada","depFacilities":"ZAU ZMP ZKC ZID ZOB ZLC ZDV ZAB ZFW ZME ZTL ZDC ZNY ZBW CYWG CYYZ"}',
  '{"facility":"ZAU","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZAU","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZAU","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZAU","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZAU","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZAU","tier":"Internal","depFacilities":"ZAU"}',
  '{"facility":"ZAU","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZBW","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZBW","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZBW","tier":"1stTier","depFacilities":"ZBW ZDC ZNY ZOB"}',
  '{"facility":"ZBW","tier":"1stTier+Canada","depFacilities":"ZBW ZDC ZNY ZOB CYOW CYUL CYYZ"}',
  '{"facility":"ZBW","tier":"1stTier+Canada","depFacilities":"ZBW ZDC ZNY ZOB CYYZ CYOW CYUL"}',
  '{"facility":"ZBW","tier":"2ndTier","depFacilities":"ZBW ZDC ZNY ZOB ZMP ZAU ZID ZTL ZJX"}',
  '{"facility":"ZBW","tier":"2ndTier+Canada","depFacilities":"ZBW ZDC ZNY ZOB ZMP ZAU ZID ZTL ZJX CYOW CYUL CYYZ"}',
  '{"facility":"ZBW","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZBW","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZBW","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZBW","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZBW","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZBW","tier":"Internal","depFacilities":"ZBW"}',
  '{"facility":"ZBW","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZDC","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZDC","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZDC","tier":"1stTier","depFacilities":"ZDC ZBW ZNY ZOB ZID ZTL ZJX"}',
  '{"facility":"ZDC","tier":"1stTier+Canada","depFacilities":"ZDC ZBW ZNY ZOB ZID ZTL ZJX"}',
  '{"facility":"ZDC","tier":"2ndTier","depFacilities":"ZDC ZBW ZNY ZOB ZID ZTL ZJX ZMA ZHU ZME ZKC ZAU ZMP"}',
  '{"facility":"ZDC","tier":"2ndTier+Canada","depFacilities":"ZDC ZBW ZNY ZOB ZID ZTL ZJX ZMA ZHU ZME ZKC ZAU ZMP CYOW CYUL CYYZ"}',
  '{"facility":"ZDC","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZDC","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZDC","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZDC","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZDC","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZDC","tier":"Internal","depFacilities":"ZDC"}',
  '{"facility":"ZDC","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZDV","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZDV","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZDV","tier":"1stTier","depFacilities":"ZDV ZLC ZLA ZAB ZMP ZKC"}',
  '{"facility":"ZDV","tier":"1stTier+Canada","depFacilities":"ZDV ZLC ZLA ZAB ZMP ZKC"}',
  '{"facility":"ZDV","tier":"2ndTier","depFacilities":"ZDV ZLC ZLA ZAB ZMP ZKC ZSE ZOA ZFW ZME ZHU ZID ZOB ZAU"}',
  '{"facility":"ZDV","tier":"2ndTier+Canada","depFacilities":"ZDV ZLC ZLA ZAB ZMP ZKC ZSE ZOA ZFW ZME ZHU ZID ZOB ZAU CYWG CYYC CYYZ"}',
  '{"facility":"ZDV","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZDV","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZDV","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZDV","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZDV","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZDV","tier":"Internal","depFacilities":"ZDV"}',
  '{"facility":"ZDV","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZFW","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZFW","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZFW","tier":"1stTier","depFacilities":"ZFW ZME ZKC ZAB ZHU"}',
  '{"facility":"ZFW","tier":"1stTier+Canada","depFacilities":"ZFW ZME ZKC ZAB ZHU"}',
  '{"facility":"ZFW","tier":"2ndTier","depFacilities":"ZFW ZME ZKC ZAB ZHU ZLA ZDV ZMP ZAU ZID ZTL ZJX ZMA"}',
  '{"facility":"ZFW","tier":"2ndTier+Canada","depFacilities":"ZFW ZME ZKC ZAB ZHU ZLA ZDV ZMP ZAU ZID ZTL ZJX ZMA"}',
  '{"facility":"ZFW","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZFW","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZFW","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZFW","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZFW","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZFW","tier":"Internal","depFacilities":"ZFW"}',
  '{"facility":"ZFW","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZHU","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZHU","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZHU","tier":"1stTier","depFacilities":"ZHU ZAB ZFW ZME ZTL ZJX ZMA"}',
  '{"facility":"ZHU","tier":"1stTier+Canada","depFacilities":"ZHU ZAB ZFW ZME ZTL ZJX ZMA"}',
  '{"facility":"ZHU","tier":"2ndTier","depFacilities":"ZHU ZAB ZFW ZME ZTL ZJX ZMA ZLA ZDV ZKC ZID ZDC"}',
  '{"facility":"ZHU","tier":"2ndTier+Canada","depFacilities":"ZHU ZAB ZFW ZME ZTL ZJX ZMA ZLA ZDV ZKC ZID ZDC"}',
  '{"facility":"ZHU","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZHU","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZHU","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZHU","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZHU","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZHU","tier":"Internal","depFacilities":"ZHU"}',
  '{"facility":"ZHU","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZID","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZID","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZID","tier":"1stTier","depFacilities":"ZID ZAU ZOB ZDC ZME ZTL ZKC"}',
  '{"facility":"ZID","tier":"1stTier+Canada","depFacilities":"ZID ZAU ZOB ZDC ZME ZTL ZKC"}',
  '{"facility":"ZID","tier":"2ndTier","depFacilities":"ZID ZAU ZOB ZDC ZME ZTL ZKC ZAB ZDV ZFW ZMP ZHU ZJX ZNY ZBW"}',
  '{"facility":"ZID","tier":"2ndTier+Canada","depFacilities":"ZID ZAU ZOB ZDC ZME ZTL ZKC ZAB ZDV ZFW ZMP ZHU ZJX ZNY ZBW CYYZ"}',
  '{"facility":"ZID","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZID","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZID","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZID","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZID","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZID","tier":"Internal","depFacilities":"ZID"}',
  '{"facility":"ZID","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZJX","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZJX","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZJX","tier":"1stTier","depFacilities":"ZJX ZMA ZHU ZTL ZDC"}',
  '{"facility":"ZJX","tier":"1stTier+Canada","depFacilities":"ZJX ZMA ZHU ZTL ZDC"}',
  '{"facility":"ZJX","tier":"2ndTier","depFacilities":"ZJX ZMA ZHU ZTL ZDC ZAB ZFW ZME ZID ZOB ZNY ZBW"}',
  '{"facility":"ZJX","tier":"2ndTier+Canada","depFacilities":"ZJX ZMA ZHU ZTL ZDC ZAB ZFW ZME ZID ZOB ZNY ZBW"}',
  '{"facility":"ZJX","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZJX","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZJX","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZJX","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZJX","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZJX","tier":"Internal","depFacilities":"ZJX"}',
  '{"facility":"ZJX","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZKC","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZKC","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZKC","tier":"1stTier","depFacilities":"ZKC ZMP ZAU ZID ZME ZFW ZAB ZDV"}',
  '{"facility":"ZKC","tier":"1stTier+Canada","depFacilities":"ZKC ZMP ZAU ZID ZME ZFW ZAB ZDV"}',
  '{"facility":"ZKC","tier":"2ndTier","depFacilities":"ZKC ZMP ZAU ZID ZME ZFW ZAB ZDV ZLC ZLA ZHU ZTL ZDC ZOB"}',
  '{"facility":"ZKC","tier":"2ndTier+Canada","depFacilities":"ZKC ZMP ZAU ZID ZME ZFW ZAB ZDV ZLC ZLA ZHU ZTL ZDC ZOB CYWG CYYZ"}',
  '{"facility":"ZKC","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZKC","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZKC","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZKC","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZKC","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZKC","tier":"Internal","depFacilities":"ZKC"}',
  '{"facility":"ZKC","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZLA","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZLA","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZLA","tier":"1stTier","depFacilities":"ZLA ZLC ZOA ZDV ZAB"}',
  '{"facility":"ZLA","tier":"1stTier+Canada","depFacilities":"ZLA ZLC ZOA ZDV ZAB"}',
  '{"facility":"ZLA","tier":"2ndTier","depFacilities":"ZLA ZLC ZOA ZDV ZAB ZSE ZMP ZKC ZFW ZHU"}',
  '{"facility":"ZLA","tier":"2ndTier+Canada","depFacilities":"ZLA ZLC ZOA ZDV ZAB ZSE ZMP ZKC ZFW ZHU CYWG CYYC"}',
  '{"facility":"ZLA","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZLA","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZLA","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZLA","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZLA","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZLA","tier":"Internal","depFacilities":"ZLA"}',
  '{"facility":"ZLA","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZLC","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZLC","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZLC","tier":"1stTier","depFacilities":"ZLC ZDV ZLA ZMP ZOA ZSE"}',
  '{"facility":"ZLC","tier":"1stTier+Canada","depFacilities":"ZLC ZDV ZLA ZMP ZOA ZSE CYEG CYWG CYYC"}',
  '{"facility":"ZLC","tier":"1stTier+Canada","depFacilities":"ZLC ZDV ZLA ZMP ZOA ZSE CYYZ CYEG"}',
  '{"facility":"ZLC","tier":"2ndTier","depFacilities":"ZLC ZDV ZLA ZMP ZOA ZSE ZAB ZKC ZAU ZOB"}',
  '{"facility":"ZLC","tier":"2ndTier+Canada","depFacilities":"ZLC ZDV ZLA ZMP ZOA ZSE ZAB ZKC ZAU ZOB CYEG CYVR CYWG CYYC CYYZ"}',
  '{"facility":"ZLC","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZLC","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZLC","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZLC","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZLC","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZLC","tier":"Internal","depFacilities":"ZLC"}',
  '{"facility":"ZLC","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZMA","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZMA","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZMA","tier":"1stTier","depFacilities":"ZMA ZJX ZHU"}',
  '{"facility":"ZMA","tier":"1stTier+Canada","depFacilities":"ZMA ZJX ZHU"}',
  '{"facility":"ZMA","tier":"2ndTier","depFacilities":"ZMA ZJX ZHU ZFW ZME ZTL ZDC"}',
  '{"facility":"ZMA","tier":"2ndTier+Canada","depFacilities":"ZMA ZJX ZHU ZFW ZME ZTL ZDC"}',
  '{"facility":"ZMA","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZMA","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZMA","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZMA","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZMA","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZMA","tier":"Internal","depFacilities":"ZMA"}',
  '{"facility":"ZMA","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZME","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZME","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZME","tier":"1stTier","depFacilities":"ZME ZTL ZID ZKC ZFW ZHU"}',
  '{"facility":"ZME","tier":"1stTier+Canada","depFacilities":"ZME ZTL ZID ZKC ZFW ZHU"}',
  '{"facility":"ZME","tier":"2ndTier","depFacilities":"ZME ZTL ZID ZKC ZFW ZHU ZAB ZDV ZMP ZAU ZOB ZDC ZJX ZMA"}',
  '{"facility":"ZME","tier":"2ndTier+Canada","depFacilities":"ZME ZTL ZID ZKC ZFW ZHU ZAB ZDV ZMP ZAU ZOB ZDC ZJX ZMA"}',
  '{"facility":"ZME","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZME","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZME","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZME","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZME","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZME","tier":"Internal","depFacilities":"ZME"}',
  '{"facility":"ZME","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZMP","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZMP","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZMP","tier":"1stTier","depFacilities":"ZMP ZAU ZOB ZKC ZDV ZLC"}',
  '{"facility":"ZMP","tier":"1stTier+Canada","depFacilities":"ZMP ZAU ZOB ZKC ZDV ZLC CYWG CYYZ"}',
  '{"facility":"ZMP","tier":"1stTier+Canada","depFacilities":"ZMP ZAU ZOB ZKC ZDV ZLC CYYZ"}',
  '{"facility":"ZMP","tier":"2ndTier","depFacilities":"ZMP ZAU ZOB ZKC ZDV ZLC ZSE ZOA ZLA ZAB ZFW ZME ZID ZDC ZNY ZBW"}',
  '{"facility":"ZMP","tier":"2ndTier+Canada","depFacilities":"ZMP ZAU ZOB ZKC ZDV ZLC ZSE ZOA ZLA ZAB ZFW ZME ZID ZDC ZNY ZBW CYEG CYWG CYYC CYYZ"}',
  '{"facility":"ZMP","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZMP","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZMP","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZMP","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZMP","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZMP","tier":"Internal","depFacilities":"ZMP"}',
  '{"facility":"ZMP","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZNY","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZNY","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZNY","tier":"1stTier","depFacilities":"ZNY ZBW ZDC ZOB"}',
  '{"facility":"ZNY","tier":"1stTier+Canada","depFacilities":"ZNY ZBW ZDC ZOB"}',
  '{"facility":"ZNY","tier":"2ndTier","depFacilities":"ZNY ZBW ZDC ZOB ZMP ZAU ZID ZTL ZJX"}',
  '{"facility":"ZNY","tier":"2ndTier+Canada","depFacilities":"ZNY ZBW ZDC ZOB ZMP ZAU ZID ZTL ZJX CYOW CYUL CYYZ"}',
  '{"facility":"ZNY","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZNY","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZNY","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZNY","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZNY","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZNY","tier":"Internal","depFacilities":"ZNY"}',
  '{"facility":"ZNY","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZOA","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZOA","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZOA","tier":"1stTier","depFacilities":"ZOA ZLA ZSE ZLC"}',
  '{"facility":"ZOA","tier":"1stTier+Canada","depFacilities":"ZOA ZLA ZSE ZLC"}',
  '{"facility":"ZOA","tier":"2ndTier","depFacilities":"ZOA ZLA ZSE ZLC ZDV ZAB ZMP"}',
  '{"facility":"ZOA","tier":"2ndTier+Canada","depFacilities":"ZOA ZLA ZSE ZLC ZDV ZAB ZMP CYWG CYVR CYYC"}',
  '{"facility":"ZOA","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZOA","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZOA","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZOA","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZOA","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZOA","tier":"Internal","depFacilities":"ZOA"}',
  '{"facility":"ZOA","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZOB","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZOB","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZOB","tier":"1stTier","depFacilities":"ZOB ZAU ZMP ZID ZDC ZNY ZBW"}',
  '{"facility":"ZOB","tier":"1stTier+Canada","depFacilities":"ZOB ZAU ZMP ZID ZDC ZNY ZBW CYYZ"}',
  '{"facility":"ZOB","tier":"2ndTier","depFacilities":"ZOB ZAU ZMP ZID ZDC ZNY ZBW ZLC ZDV ZKC ZME ZTL ZJX"}',
  '{"facility":"ZOB","tier":"2ndTier+Canada","depFacilities":"ZOB ZAU ZMP ZID ZDC ZNY ZBW ZLC ZDV ZKC ZME ZTL ZJX CYOW CYUL CYWG CYYZ"}',
  '{"facility":"ZOB","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZOB","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZOB","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZOB","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZOB","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZOB","tier":"Internal","depFacilities":"ZOB"}',
  '{"facility":"ZOB","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZSE","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZSE","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZSE","tier":"1stTier","depFacilities":"ZSE ZOA ZLC"}',
  '{"facility":"ZSE","tier":"1stTier+Canada","depFacilities":"ZSE ZOA ZLC CYEG CYVR CYYC"}',
  '{"facility":"ZSE","tier":"1stTier+Canada","depFacilities":"ZSE ZOA ZLC CYVR CYYC CYEG"}',
  '{"facility":"ZSE","tier":"2ndTier","depFacilities":"ZSE ZOA ZLC ZMP ZDV ZLA"}',
  '{"facility":"ZSE","tier":"2ndTier+Canada","depFacilities":"ZSE ZOA ZLC ZMP ZDV ZLA CYEG CYVR CYWG CYYC"}',
  '{"facility":"ZSE","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZSE","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZSE","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZSE","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZSE","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZSE","tier":"Internal","depFacilities":"ZSE"}',
  '{"facility":"ZSE","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}',
  '{"facility":"ZTL","tier":"10West","depFacilities":"ZAB ZDV ZFW ZHU ZKC ZLA ZLC ZMP ZOA ZSE"}',
  '{"facility":"ZTL","tier":"12West","depFacilities":"ZAB ZAU ZDV ZFW ZHU ZKC ZLA ZLC ZME ZMP ZOA ZSE"}',
  '{"facility":"ZTL","tier":"1stTier","depFacilities":"ZTL ZID ZDC ZJX ZME ZHU"}',
  '{"facility":"ZTL","tier":"1stTier+Canada","depFacilities":"ZTL ZID ZDC ZJX ZME ZHU"}',
  '{"facility":"ZTL","tier":"2ndTier","depFacilities":"ZTL ZID ZDC ZJX ZME ZHU ZAB ZFW ZKC ZAU ZOB ZNY ZBW ZMA"}',
  '{"facility":"ZTL","tier":"2ndTier+Canada","depFacilities":"ZTL ZID ZDC ZJX ZME ZHU ZAB ZFW ZKC ZAU ZOB ZNY ZBW ZMA"}',
  '{"facility":"ZTL","tier":"6West","depFacilities":"ZLA ZLC ZDV ZOA ZAB ZSE"}',
  '{"facility":"ZTL","tier":"ALL","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL"}',
  '{"facility":"ZTL","tier":"ALL+Canada","depFacilities":"ZAB ZAU ZBW ZDC ZDV ZFW ZHU ZID ZJX ZKC ZLA ZLC ZMA ZME ZMP ZNY ZOA ZOB ZSE ZTL CZE CZM CZU CZV CZW CZY"}',
  '{"facility":"ZTL","tier":"EastCoast","depFacilities":"ZBW ZNY ZDC ZJX ZMA"}',
  '{"facility":"ZTL","tier":"Gulf","depFacilities":"ZJX ZMA ZHU"}',
  '{"facility":"ZTL","tier":"Internal","depFacilities":"ZTL"}',
  '{"facility":"ZTL","tier":"WestCoast","depFacilities":"ZSE ZOA ZLA"}'
];

function selectFacility() {
  var inputFacility = document.getElementById("depFacility").value;
  var inputTier = document.getElementById("tier").value;

  for (i in facilityList) {
    var obj = JSON.parse(facilityList[i]);
    if (obj.facility == inputFacility) {
      if (obj.tier == inputTier) {
        document.getElementById("depFacilities").value = "(" + inputTier + ") " + obj.depFacilities;
      }
    }
  }
}